safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date
exclude:     boglesite.komodoproject
redirects:   true
