safe:       false
port:       4000
baseurl:    /

source:      .
destination: ./_site
plugins_dir: ./_plugins

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   date
redirects:   true
